trigger: none

name: deploySubscription

pool:
  vmImage: ubuntu-latest

variables:
  ServiceConnectionName: "deploy-bicep"
  RunNumber: $(Build.BuildNumber)
  DeploymentName: "sub-vend-$(RunNumber)"
  ManagementGroupId : "58f7c0d7-3191-43d3-a803-62d8805626de" # Tenant Root Group ID
  Location: "australiaeast"
  TemplateParameterFile: "parameters/subscription/identity-sub.parameters.json"
  TemplateFile: "subscription.bicep"

jobs:
- job: SubscriptonVending
  steps:

  - task: AzureCLI@2
    displayName: Az CLI Deploy Subscription
    name: create_mgs
    inputs:
      workingDirectory: $(Build.SourcesDirectory)
      azureSubscription: $(ServiceConnectionName)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment mg create \
        --name $(DeploymentName) \
        --parameters $(TemplateParameterFile) \
        --location $(Location) \
        --management-group-id $(ManagementGroupId) \
        --template-file $(TemplateFile) \
        